# Simple Web Application Workflow
version: "1.0"

project:
  name: simple-web-app-workflow
  type: web
  description: A simple web application development workflow example
  language_policy:
    customer_facing: "ja"
    development: "en"
    documentation: "en"
    code_comments: "en"
    commit_messages: "en"

agents:
  include_templates:
    - core
    - quality
    - web-development

workflow:
  stages:
    - name: requirements-gathering
      description: Gather requirements from client
      agents:
        - client-liaison
      execution_mode: sequential
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: abort
    
    - name: planning
      description: Create development plan
      agents:
        - planner
      execution_mode: sequential
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: abort
    
    - name: api-design
      description: Design API specification
      agents:
        - api-designer
      execution_mode: sequential
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: abort
    
    - name: implementation
      description: Develop backend and frontend code
      agents:
        - backend-dev
        - frontend-dev
      execution_mode: parallel
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: retry
    
    - name: review-and-qa
      description: Review and test the application
      agents:
        - reviewer-be
        - reviewer-fe
        - tester
        - quality-auditor
      execution_mode: parallel
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: retry
    
    - name: integration
      description: Integrate all components
      agents:
        - integrator
      execution_mode: sequential
      gate:
        required_status: OK
        allow_warnings: true
        max_errors: 0
      on_failure: abort

  error_handling:
    retry_policy:
      max_attempts: 3
      backoff_type: exponential
      initial_delay_ms: 1000
      max_delay_ms: 60000
      multiplier: 2.0
      jitter: true
      jitter_factor: 0.1
    
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      success_threshold: 3
      half_open_max_calls: 3
      recovery_timeout_ms: 60000

  global_timeout_ms: 3600000